apiVersion: apps/v1
kind: Deployment
metadata:
  name:  digisense-masters
  labels:
    app:  digisense-masters
spec:
  selector:
    matchLabels:
      app: digisense-masters
  replicas: 1
  template:
    metadata:
      labels:
        app:  digisense-masters
    spec:
      containers:
      - name:  digisense-masters
        image:  asia.gcr.io/digisense-fd-236012/masters
        resources:
         limits:
          cpu: 600m
         requests:
          memory: 85Mi
        env:
        - name: DBHOST
          value: digisense-mysql
        - name: DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: DevelopmentType
          value: Dev
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: digisense-fd-236012-f36d767c79bc.json
        - name: gcbucketdev
          value: gcavailabilitydevuat-bucket01
        - name: StorageDomain
          value: https://storage.googleapis.com/
        ports:
        - containerPort:  80
      restartPolicy: Always