apiVersion: apps/v1
kind: Deployment
metadata:
  name:  digisense-portal
  labels:
    app:  digisense-portal
spec:
  selector:
    matchLabels:
      app: digisense-portal
  replicas: 1
  template:
    metadata:
      labels:
        app:  digisense-portal
    spec:
      containers:
      - name:  digisense-portal
        image:  asia.gcr.io/digisense-fd-236012/adminportal
        resources:
         limits:
          cpu: 1500m
          memory: 700Mi
         requests:
          cpu: 100m
          memory: 100Mi
        env:
        - name: DBHOST
          value: digisense-mysql
        - name: DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: DevelopmentType
          value: Dev
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: digisense-fd-236012-f36d767c79bc.json
        - name: gcbucketdev
          value: gcavailabilitydevuat-bucket01
        - name: StorageDomain
          value: https://storage.googleapis.com/
        - name: UserManualFileType
          value: "3"
        - name: TimeZoneName
          value: Asia/Kolkata
        ports:
        - containerPort:  80
      restartPolicy: Always