apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: digisense-cron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: asia.gcr.io/digisense-fd-236012/generalcustapp-cronjob
        resources:
         limits:
          cpu: 25m
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
