apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: digisense-cron
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: asia.gcr.io/digisense-fd-236012/generalcustapp-cronjob
	    env:
            - name: DBHOST
              value: digisense-mysql
          restartPolicy: OnFailure
