apiVersion: apps/v1
kind: Deployment
metadata:
  name:  digisense-fromfdw
  labels:
    app:  digisense-fromfdw
spec:
  selector:
    matchLabels:
      app: digisense-fromfdw
  replicas: 1
  template:
    metadata:
      labels:
        app:  digisense-fromfdw
    spec:
      containers:
      - name:  digisense-fromfdw
        image:  asia.gcr.io/digisense-fd-236012/getfromfdw
        resources:
         limits:
          cpu: 100m
        env:
        - name: DBHOST
          value: digisense-mysql
        - name: DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: SMSUSER
          value: "7550223074"
        - name: SMSPASSWORD
          value: mahindra%40123
        - name: SMSGATEWAY
          value: https://bulkpush.mytoday.com/BulkSms/SingleMsgApi
        - name: SMSFEEDID
          value: "382593"
        - name: NewCustDeviceID
          value: New_Customer
        - name: AppName1
          value: MTracWorld
        - name: AppName
          value: TracWorld!
        - name: AppDownloadURL
          value: https://custappdev.mahindradigisense.com/AppShare/Download.html
        ports:
        - containerPort:  80
      restartPolicy: Always