apiVersion: apps/v1
kind: Deployment
metadata:
  name:  digisense-banners
  labels:
    app:  digisense-banners
spec:
  selector:
    matchLabels:
      app: digisense-banners
  replicas: 4
  template:
    metadata:
      labels:
        app:  digisense-banners
    spec:
      containers:
      - name:  digisense-enquiry
        image:  asia.gcr.io/digisense-fd-236012/banners
        resources:
         limits:
          cpu: 22m
        env:
        - name: DBHOST
          value: digisense-mysql
        - name: DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort:  80
      restartPolicy: Always