apiVersion: apps/v1
kind: Deployment
metadata:
  name:  prod-digisense-masters
  labels:
    app:  prod-digisense-masters
spec:
  selector:
    matchLabels:
      app: prod-digisense-masters
  replicas: 1
  template:
    metadata:
      labels:
        app:  prod-digisense-masters
    spec:
      containers:
      - name:  digisense-masters
        image:  asia.gcr.io/generalcustomeravailability/prod_masters
        resources:
         limits:
          cpu: 800m
          memory: 560Mi
         requests:
          cpu: 100m
          memory: 85Mi
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: private-ip-secret
              key: db_host
        - name: DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: DevelopmentType
          value: Live
        - name: gcbucketdev
          value: gcavailabilitydevuat-bucket01
        - name: gcbucket
          value: gcavailability-bucket01
        - name: StorageDomain
          value: https://storage.googleapis.com/
        - name: cloudpath
          value: GeneralCustomerApp/masters/Resources/Images/
        ports:
        - containerPort:  80
      restartPolicy: Always