apiVersion: apps/v1
kind: Deployment
metadata:
  name:  prod-digisense-masters
  labels:
    app:  prod-digisense-masters
spec:
  selector:
    matchLabels:
      app: prod-digisense-masters
  replicas: 1
  template:
    metadata:
      labels:
        app:  prod-digisense-masters
    spec:
      containers:
      - name:  digisense-masters
        image:  asia.gcr.io/generalcustomeravailability/prod_masters
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: private-ip-secret
              key: db_host
        - name: DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort:  80
      restartPolicy: Always