apiVersion: v1
kind: Service
metadata:
  name: prod-digisense-portal-svc
spec:
  selector:
    app: prod-digisense-portal
  type: NodePort
  ports:
  - port: 8001 
    targetPort: 80 
    protocol: TCP