apiVersion: apps/v1
kind: Deployment
metadata:
  name:  prod-digisense-portal
  labels:
    app:  prod-digisense-portal
spec:
  selector:
    matchLabels:
      app: prod-digisense-portal
  replicas: 1
  template:
    metadata:
      labels:
        app:  prod-digisense-portal
    spec:
      containers:
      - name:  prod-digisense-portal
        image:  asia.gcr.io/generalcustomeravailability/prod_adminportal
        resources:
         limits:
          cpu: 1500m
          memory: 700Mi
         requests:
          cpu: 100m
          memory: 200Mi
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: private-ip-secret
              key: db_host
        - name: DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: DevelopmentType
          value: Live
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: generalcustomeravailability-c9c58a28f833.json
        - name: gcbucket
          value: gcavailability-bucket01
        - name: StorageDomain
          value: https://storage.googleapis.com/
        - name: UserManualFileType
          value: "3"
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: INSTANCE_CONNECTION_NAME
          value: generalcustomeravailability:asia-south1:gcavailability-mysql8-1
        ports:
        - containerPort:  80
      serviceAccount: default
      serviceAccountName: default
      restartPolicy: Always