apiVersion: apps/v1
kind: Deployment
metadata:
  name:  prod-digisense-subscription
  labels:
    app:  prod-digisense-subscription
spec:
  selector:
    matchLabels:
      app: prod-digisense-subscription
  replicas: 1
  template:
    metadata:
      labels:
        app:  prod-digisense-subscription
    spec:
      containers:
      - name:  digisense-subscription
        image:  asia.gcr.io/generalcustomeravailability/prod_subscription
        resources:
         limits:
          cpu: 500m
          memory: 260Mi
         requests:
          cpu: 50m
          memory: 85Mi
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: private-ip-secret
              key: db_host
        - name: DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: DevelopmentType
          value: Live
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: digisense-fd-236012-f36d767c79bc.json
        - name: EncryptServiceURL
          value: https://dev.hnsonline.com/GeneralCustomerAPI/api/Security/Enrypt_GeneralCustomerApp?request=
        - name: DecryptServiceURL
          value: https://dev.hnsonline.com/GeneralCustomerAPI/api/Security/Decrypt_GeneralCustomerApp?request=
        - name: gcbucketdev
          value: gcavailabilitydevuat-bucket01
        - name: StorageDomain
          value: https://storage.googleapis.com/
        - name: Database
          value: digisense
        - name: gcbucket
          value: gcavailability-bucket01
        - name: SAC_CODE
          value: "998599"
        - name: KUNNR
          value: A042111
        - name: WERKS
          value: FMKT
        - name: SORG
          value: F001
        - name: SubscriptionUpdateURL
          value: https://apiqa1.mahindradigisense.com/api/v2/subscriptionupdate
        - name: ProdDigisenseAPIKey
          value: 5fdf60e35d97fd70c6676050f64dac1d127ffec5f2260dd6d2607e6b231fd234
        - name: Type
          value: Authorization
        - name: DigisenseLoginURL
          value: https://apiqa1.mahindradigisense.com/api/v2/login
        - name: ProdDigisenseLoginURL
          value: https://api.mahindradigisense.com/api/v2/login
        - name: DigisenseAPIKey
          value: 302d7814e01de206d1e02640b95ba39c8a3f2447a1c3aaadfff6d93aa600b9ce
        ports:
        - containerPort:  80
      restartPolicy: Always