apiVersion: apps/v1
kind: Deployment
metadata:
  name:  prod-digisense-banners
  labels:
    app:  prod-digisense-banners
spec:
  selector:
    matchLabels:
      app: prod-digisense-banners
  replicas: 1
  template:
    metadata:
      labels:
        app:  prod-digisense-banners
    spec:
      containers:
      - name:  prod-digisense-banners
        image:  asia.gcr.io/generalcustomeravailability/prod_banners
        resources:
         limits:
          cpu: 700m
          memory: 600Mi
         requests:
          cpu: 100m
          memory: 200Mi
        env:
        - name: DBHOST
          value: digisense-mysql
        - name: DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: DigisenseDeviceTokenURL
          value: https://apiqa1.mahindradigisense.com/api/v2/devicetoken
        - name: DigisenseLoginURL
          value: https://apiqa1.mahindradigisense.com/api/v2/login
        - name: DigisenseAPIKey
          value: 302d7814e01de206d1e02640b95ba39c8a3f2447a1c3aaadfff6d93aa600b9ce
        ports:
        - containerPort:  80
      restartPolicy: Always