apiVersion: apps/v1
kind: Deployment
metadata:
  name:  prod-digisense-portal
  labels:
    app:  prod-digisense-portal
spec:
  selector:
    matchLabels:
      app: prod-digisense-portal
  replicas: 2
  template:
    metadata:
      labels:
        app:  prod-digisense-portal
    spec:
      containers:
      - name:  prod-digisense-portal
        image:  asia.gcr.io/generalcustomeravailability/prod_adminportal
        resources:
         limits:
          cpu: 900m
          memory: 700Mi
         requests:
          cpu: 100m
          memory: 200Mi
        env:
        - name: DBHOST
          value: "10.185.48.31"
        - name: DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort:  80
      restartPolicy: Always