apiVersion: apps/v1
kind: Deployment
metadata:
  name:  prod-digisense-enquiry
  labels:
    app:  prod-digisense-enquiry
spec:
  selector:
    matchLabels:
      app: prod-digisense-enquiry
  replicas: 1
  template:
    metadata:
      labels:
        app:  prod-digisense-enquiry
    spec:
      containers:
      - name:  prod-digisense-enquiry
        image:  asia.gcr.io/generalcustomeravailability/prod_enquiry
        resources:
         limits:
          cpu: 600m
          memory: 260Mi
         requests:
          memory: 85Mi
        env:
        - name: DBHOST
          value: digisense-mysql
        - name: DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort:  80
      restartPolicy: Always