apiVersion: apps/v1
kind: Deployment
metadata:
  name:  prod-digisense-unifiedlogin
  labels:
    app:  prod-digisense-unifiedlogin
spec:
  selector:
    matchLabels:
      app: prod-digisense-unifiedlogin
  replicas: 1
  template:
    metadata:
      labels:
        app:  prod-digisense-unifiedlogin
    spec:
      containers:
      - name:  digisense-unifiedlogin
        image:  asia.gcr.io/generalcustomeravailability/prod_unifiedlogin
        resources:
         limits:
          cpu: 180m
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: private-ip-secret
              key: db_host
        - name: DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: SMSGATEWAY
          value: https://bulkpush.mytoday.com/BulkSms/SingleMsgApi
        - name: SMSFEEDID
          value: "382593"
        - name: SMSUSER
          value: "7550223074"
        - name: SMSPASSWORD
          value: mahindra%40123
        - name: DigisenseAPIKey
          value: 302d7814e01de206d1e02640b95ba39c8a3f2447a1c3aaadfff6d93aa600b9ce
        - name: DigisenseLoginURL
          value: https://apiqa1.mahindradigisense.com/api/v2/login
        - name: DigisenseUpdateProfileURL
          value: https://apiqa1.mahindradigisense.com/api/v2/profile?isSec=true
        - name: DigisenseChangePINURL
          value: https://apiqa1.mahindradigisense.com/api/v2/changepin
        - name: DefaultServiceAdvisor
          value: "18004256576"
        - name: DefaultServiceAdvisorName
          value: "Connect Mahindra"
        ports:
        - containerPort:  80
      restartPolicy: Always