apiVersion: apps/v1
kind: Deployment
metadata:
  name:  prod-digisense-subscription
  labels:
    app:  prod-digisense-subscription
spec:
  selector:
    matchLabels:
      app: prod-digisense-subscription
  replicas: 1
  template:
    metadata:
      labels:
        app:  prod-digisense-subscription
    spec:
      containers:
      - name:  digisense-subscription
        image:  asia.gcr.io/generalcustomeravailability/prod_subscription
        resources:
         limits:
          cpu: 700m
          memory: 260Mi
         requests:
          memory: 85Mi
        env:
        - name: DBHOST
          value: digisense-mysql
        - name: DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: DevelopmentType
          value: Live
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: digisense-fd-236012-f36d767c79bc.json
        - name: EncryptServiceURL
          value: https://dev.hnsonline.com/GeneralCustomerAPI/api/Security/Enrypt_GeneralCustomerApp?request=
        - name: DecryptServiceURL
          value: https://dev.hnsonline.com/GeneralCustomerAPI/api/Security/Decrypt_GeneralCustomerApp?request=
        - name: gcbucketdev
          value: gcavailabilitydevuat-bucket01
        - name: StorageDomain
          value: https://storage.googleapis.com/
        - name: Database
          value: digisense
        - name: gcbucket
          value: gcavailability-bucket01
        - name: SAC_CODE
          value: "998599"
        - name: KUNNR
          value: A042111
        - name: WERKS
          value: FMKT
        - name: SORG
          value: F001
        ports:
        - containerPort:  80
      restartPolicy: Always