apiVersion: apps/v1
kind: Deployment
metadata:
  name:  digisense-banners
  labels:
    app:  digisense-banners
spec:
  selector:
    matchLabels:
      app: digisense-banners
  replicas: 2
  template:
    metadata:
      labels:
        app:  digisense-banners
    spec:
      containers:
      - name:  digisense-enquiry
        image:  asia.gcr.io/generalcustomeravailability/prod_banners
        resources:
         limits:
          cpu: 200m
          memory: 400Mi
         requests:
          cpu: 100m
          memory: 200Mi
        env:
        - name: DBHOST
          value: digisense-mysql
        - name: DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort:  80
      restartPolicy: Always