apiVersion: apps/v1
kind: Deployment
metadata:
  name:  prod-digisense-portal
  labels:
    app:  prod-digisense-portal
spec:
  selector:
    matchLabels:
      app: prod-digisense-portal
  replicas: 1
  template:
    metadata:
      labels:
        app:  prod-digisense-portal
    spec:
      containers:
      - name:  prod-digisense-portal
        image:  asia.gcr.io/generalcustomeravailability/prod_adminportal
        resources:
         limits:
          cpu: 900m
          memory: 700Mi
         requests:
          cpu: 100m
          memory: 200Mi
        env:
        - name: DBHOST
          value: "10.185.48.31"
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: INSTANCE_CONNECTION_NAME
          value: generalcustomeravailability:asia-south1:gcavailability-mysql8-1
        - name: DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort:  80
      serviceAccount: default
      serviceAccountName: default
      restartPolicy: Always