apiVersion: apps/v1
kind: Deployment
metadata:
  name:  prod-digisense-fromfdw
  labels:
    app:  prod-digisense-fromfdw
spec:
  selector:
    matchLabels:
      app: prod-digisense-fromfdw
  replicas: 1
  template:
    metadata:
      labels:
        app:  prod-digisense-fromfdw
    spec:
      containers:
      - name:  prod-digisense-fromfdw
        image:  asia.gcr.io/generalcustomeravailability/prod_getfromfdw
        resources:
         limits:
          cpu: 1200m
          memory: 700Mi
         requests:
          cpu: 100m
          memory: 85Mi
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: private-ip-secret
              key: db_host
        - name: DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: SMSUSER
          value: "7550223074"
        - name: SMSPASSWORD
          value: mahindra%40123
        - name: SMSGATEWAY
          value: https://bulkpush.mytoday.com/BulkSms/SingleMsgApi
        - name: SMSFEEDID
          value: "382593"
        - name: NewCustDeviceID
          value: New_Customer
        ports:
        - containerPort:  80
      restartPolicy: Always