apiVersion: apps/v1
kind: Deployment
metadata:
  name:  prod-digisense-mandi
  labels:
    app:  prod-digisense-mandi
spec:
  selector:
    matchLabels:
      app: prod-digisense-mandi
  replicas: 1
  template:
    metadata:
      labels:
        app:  prod-digisense-mandi
    spec:
      containers:
      - name:  prod-digisense-mandi
        image:  asia.gcr.io/generalcustomeravailability/prod_mandi
        resources:
         limits:
          cpu: 400m
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: private-ip-secret
              key: db_host
        - name: DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort:  80
      restartPolicy: Always