apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-mysql-dep
spec:
  selector:
    matchLabels:
      app: prod-mysql
  template:
    metadata:
      labels:
        app: prod-mysql
    spec:
      serviceAccountName: default
      containers:
      - name: prod-mysql
        env:
        - name: DB_USER
          value: root
        - name: DB_NAME
          value: dev_encrypted_generalcustomerapp
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
      - name: cloud-sql-proxy
        # It is recommended to use the latest version of the Cloud SQL proxy
        # Make sure to update on a regular schedule!
        image: gcr.io/cloudsql-docker/gce-proxy:1.17
        command:
          - "/cloud_sql_proxy"

          # If connecting from a VPC-native GKE cluster, you can use the
          # following flag to have the proxy connect over private IP
          # - "-ip_address_types=PRIVATE"

          # Replace DB_PORT with the port the proxy should listen on
          # Defaults: MySQL: 3306, Postgres: 5432, SQLServer: 1433
          - "-instances=generalcustomeravailability:asia-south1:gcavailability-mysql8-1=tcp:3306"
        securityContext:
          # The default Cloud SQL proxy image runs as the
          # "nonroot" user and group (uid: 65532) by default.
        # runAsNonRoot: true